version: "3.8"

services:
  db:
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
  app:
    depends_on:
      - db
    restart: on-failure
    image: books-service
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:mysql://mysqldb:$MYSQL_DOCKER_PORT/$MYSQL_DATABASE",
      "spring.datasource.username" : "$MYSQL_USER",
      "spring.datasource.password" : "$MYSQL_PASSWORD",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
      "spring.jpa.hibernate.ddl-auto" : "validate",
      "spring.liquibase.enabled" : "true",
      "jwt.expiration" : "$JWT_EXPIRATION",
      "jwt.secret" : "$JWT_SECRET"
      }'